global:
  smtp_smarthost: ${SMTP_SMARTHOST}      
  smtp_from: ${SMTP_FROM}              
  smtp_auth_username: ${SMTP_USERNAME}  
  smtp_auth_password: ${SMTP_PASSWORD}  
  smtp_require_tls: true

route:
  receiver: 'email-alert'

receivers:
- name: 'email-alert'
  email_configs:
  - to: ${SMTP_TO}  
    send_resolved: true
