services:
  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    ports:
      - 8000:8000
  
  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    ports:
      - 8501:8501
    environment:
      - SERVER_HOST=server
      - SERVER_PORT=8000
    depends_on:
      - server
    entrypoint: ./entrypoint.sh