global:
  scrape_interval: 15s        
  evaluation_interval: 15s    

rule_files:
  - "alerts.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]  

scrape_configs:
  - job_name: "health"
    static_configs:
    - targets: ["server:8000"]
    metrics_path: /health
  - job_name: "fastapi"
    static_configs:
      - targets: ["server:8000"]  
    metrics_path: /metrics          